"""
File-loader / settings panels shown inside the app's tabs when data is missing.

When the app is launched without ``--eigenvec`` (or without an annotation), the
PCA / Annotation tabs host these loader panels instead of the plots/table, and a
"Settings" tab hosts the remaining CLI options. The user points at server-side
file paths (typing, or via the Browse file-browser modal), reads their columns,
and clicks Load — which relaunches the process with the composed arguments (see
``callbacks/setup.py`` and ``relaunch.py``).

The Settings fields are generated by introspecting the argparse parser
(``args.create_parser``) so the form stays in sync with the CLI automatically.
"""

import argparse
import re

import dash_bootstrap_components as dbc
from dash import html, dcc

from ..args import create_parser, float_0_1


# Field groupings by CLI dest.
EIGENVEC_FIELDS = ['eigenvec', 'dim', 'eigenvecID', 'selectedID', 'subsetID']
ANNOTATION_DEPENDENT = ['annotationID', 'latitude', 'longitude', 'time', 'group', 'group_shape']
ANNOTATION_FIELDS = ['annotation', 'merge_embedded_annotation'] + ANNOTATION_DEPENDENT
PRIMARY_ARGS = EIGENVEC_FIELDS + ANNOTATION_FIELDS
# Internal flags not shown as form fields.
_INTERNAL_ARGS = ['setup', 'ignore_embedded_annotation']


def settings_arg_names():
    """CLI dests that are *only* in the Settings tab (not a file/column field)."""
    return [a.dest for a in create_parser()._actions
            if a.option_strings and a.dest not in ('help',)
            and a.dest not in PRIMARY_ARGS and a.dest not in _INTERNAL_ARGS]


def all_arg_names():
    """Every CLI dest the Settings tab shows (the file/column fields included)."""
    return [a.dest for a in create_parser()._actions
            if a.option_strings and a.dest not in ('help',)
            and a.dest not in _INTERNAL_ARGS]


def _actions_by_dest():
    return {a.dest: a for a in create_parser()._actions if a.option_strings}


def _arg(name, id_type='setup-arg'):
    """Pattern-matching id so one callback can collect every field via ALL.

    The loader panels use ``setup-arg``; the Settings tab mirrors *every*
    parameter under ``settings-arg`` so the two can coexist without colliding.
    """
    return {'type': id_type, 'name': name}


def _initial(args, dest, fallback=None):
    """Prefill value: honour any args passed alongside the missing --eigenvec."""
    val = getattr(args, dest, None)
    return val if val is not None else fallback


def _field_component(action, args, id_type='setup-arg'):
    """Build the input component for one argparse action, prefilled from args."""
    dest = action.dest
    comp_id = _arg(dest, id_type)
    default = _initial(args, dest, action.default)

    if isinstance(action, argparse._StoreTrueAction) or action.nargs == 0:
        return dbc.Checkbox(id=comp_id, value=bool(default))
    if action.choices is not None:
        return dcc.Dropdown(
            id=comp_id, clearable=False, value=default,
            options=[{'label': str(c), 'value': c} for c in action.choices],
        )
    if action.type is int:
        return dbc.Input(id=comp_id, type='number', step=1, value=default)
    if action.type in (float, float_0_1):
        return dbc.Input(id=comp_id, type='number', step=0.05, value=default)
    return dbc.Input(id=comp_id, type='text',
                     value='' if default is None else str(default))


def _labeled_row(label, component, help_text=None):
    return dbc.Row(
        [
            dbc.Label(label, width=4, style={'fontWeight': 500, 'textAlign': 'right'}),
            dbc.Col(
                [component] + ([html.Small(help_text, className='text-muted')]
                               if help_text else []),
                width=8,
            ),
        ],
        className='mb-2', align='center',
    )


def _file_row(label, args, action, browse_id, help_text):
    """A file-path row: text input + a Browse button opening the file modal."""
    return _labeled_row(
        label,
        dbc.InputGroup([
            _field_component(action, args),
            dbc.Button('Browse…', id=browse_id, color='light', n_clicks=0),
        ]),
        help_text,
    )


def _details_style(args, file_dest):
    """Hide a loader's second step until Read succeeds.

    A path already prefilled (e.g. after Restart) means its columns are known,
    so the step starts open in that case.
    """
    return {} if _initial(args, file_dest) else {'display': 'none'}


def _dependent_dropdown(args, dest, label, help_text):
    """A file-dependent dropdown, options filled after 'Read'."""
    value = _initial(args, dest)
    options = [{'label': value, 'value': value}] if value else []
    comp = dcc.Dropdown(id=_arg(dest), options=options, value=value,
                        clearable=True, placeholder='(not set)')
    return _labeled_row(label, comp, help_text)


def _id_list_or_pattern_row(args, dest, label, list_placeholder, help_text):
    """A 'pick from list' / 'type a wildcard pattern' row for an ID-set field
    (selectedID, subsetID): a List-mode multi-select dropdown or a Pattern-mode
    text input (fnmatch wildcards, e.g. "*.SG"), toggled by a small radio
    switch. Both widgets stay mounted — only their wrapper's visibility
    toggles — so the dropdown's already-fetched options survive switching
    modes back and forth instead of needing to be refetched.
    """
    raw = _initial(args, dest)
    tokens = None
    if isinstance(raw, str) and raw:
        tokens = [s for s in re.split(r'[;,]', raw) if s.strip()] or None
    is_pattern = bool(tokens) and any(ch in tok for tok in tokens for ch in '*?[')
    options = [{'label': s, 'value': s} for s in tokens] if (tokens and not is_pattern) else []
    key = dest.lower()
    list_dd = dcc.Dropdown(
        id=_arg(dest), multi=True, options=options,
        value=None if is_pattern else tokens,
        placeholder=list_placeholder,
    )
    pattern_input = dbc.Input(
        id=f'{key}-pattern', type='text', debounce=True,
        placeholder='e.g. *.SG, !*.DG',
        value=raw if is_pattern else '',
    )
    return _labeled_row(
        label,
        html.Div([
            dbc.RadioItems(
                id=f'{key}-mode', inline=True,
                options=[{'label': 'List', 'value': 'list'},
                        {'label': 'Pattern', 'value': 'pattern'}],
                value='pattern' if is_pattern else 'list',
                style={'fontSize': '13px', 'marginBottom': '4px'},
            ),
            html.Div(list_dd, id=f'{key}-list-wrap',
                    style={'display': 'none'} if is_pattern else {}),
            html.Div(pattern_input, id=f'{key}-pattern-wrap',
                    style={} if is_pattern else {'display': 'none'}),
        ]),
        help_text,
    )


def eigenvec_loader_panel(args):
    """PCA-tab content when no eigenvec is loaded: the eigenvec loader."""
    by = _actions_by_dest()
    eid_value = _initial(args, 'eigenvecID')
    eigenvec_id_dd = dcc.Dropdown(
        id=_arg('eigenvecID'), clearable=False, value=eid_value,
        options=[{'label': eid_value, 'value': eid_value}] if eid_value else [],
        placeholder='(not set)',
    )
    # subsetID: which samples are loaded at all (unlike selectedID, which only
    # picks the initial highlight among whatever gets loaded).
    subset_row = _id_list_or_pattern_row(
        args, 'subsetID', 'Load only IDs', '(load all samples)',
        'Only these samples are loaded, everything else is skipped entirely — '
        'pick from the list, or switch to Pattern and type wildcards like '
        '*.SG (comma- or semicolon-separated for several; prefix with "!" to '
        'exclude, e.g. "!*.DG" for everyone but *.DG). Leave empty to load all.'
    )
    selected_row = _id_list_or_pattern_row(
        args, 'selectedID', 'Selected IDs', '(all samples)',
        'Which samples start selected — pick from the list, or switch to '
        'Pattern and type wildcards like *.SG (comma- or semicolon-separated '
        'for several; prefix with "!" to exclude, e.g. "!*.DG" for everyone '
        'but *.DG). Leave empty to select all.'
    )
    return dbc.Container(
        [
            html.H4('Load eigenvec data', className='mt-3'),
            html.P('Point at a PLINK eigenvec file to start the PCA.',
                   className='text-muted'),
            _file_row('Eigenvec file *', args, by['eigenvec'], 'browse-eigenvec',
                      'Type a server-side path, or Browse.'),
            html.Div(dbc.Button('Read', id='read-eigenvec-btn', color='secondary',
                                n_clicks=0), className='my-2'),
            html.Div(id='eigenvec-read-status', className='mb-2'),
            # Second step: revealed by Read (see callbacks/setup.py:read_eigenvec).
            html.Div(
                [
                    html.Hr(),
                    _labeled_row('Dimension columns', _field_component(by['dim'], args),
                                 'Comma-separated (e.g., PC1,PC2,PC3). '
                                 'Auto-detects if left empty.'),
                    _labeled_row('Eigenvec ID column', eigenvec_id_dd,
                                 'Defaults to the first column.'),
                    subset_row,
                    selected_row,
                    html.Div(dbc.Button('Load', id='pca-load-btn', color='primary',
                                        size='lg', n_clicks=0), className='mt-3'),
                    html.Div(id='pca-load-status', className='mt-2'),
                ],
                id='eigenvec-details',
                style=_details_style(args, 'eigenvec'),
            ),
        ],
        style={'maxWidth': '760px'},
    )


def _annotation_second_step(args):
    """Dropdowns + Load, revealed once the annotation columns are known —
    shared by both the plain and embedded-aware annotation_loader_panel.
    """
    return html.Div(
        [
            html.Hr(),
            # Irrelevant in embedded-only mode (no separate file to match IDs
            # against — the eigenvec's own 'id' column is used as-is); hidden
            # by use_embedded_annotation / shown again by the other two modes.
            html.Div(
                _dependent_dropdown(args, 'annotationID', 'Annotation ID column',
                                    'Column matching the eigenvec IDs.'),
                id='annotationid-row',
            ),
            _dependent_dropdown(args, 'latitude', 'Latitude column',
                                'Enables the map when latitude + longitude are set.'),
            _dependent_dropdown(args, 'longitude', 'Longitude column', 
                                'Enables the map when latitude + longitude are set.'),
            _dependent_dropdown(args, 'time', 'Time column',
                                'Enables the time plot.'),
            _dependent_dropdown(args, 'group', 'Group / colour column',
                                'Default grouping for colour.'),
            _dependent_dropdown(args, 'group_shape', 'Group / shape column',
                                'Default grouping for marker shape (categorical).'),
            html.Div(dbc.Button('Load', id='annotation-load-btn', color='primary',
                                size='lg', n_clicks=0), className='mt-3'),
            html.Div(id='annotation-load-status', className='mt-2'),
        ],
        id='annotation-details',
        style=_details_style(args, 'annotation'),
    )


def annotation_loader_panel(args, show_embedded_option=False, has_embedded_annotation_cols=False):
    """Annotation-tab content when no annotation is loaded: the annotation loader.

    Without ``show_embedded_option`` (the eigenvec is loaded and definitely has
    no extra columns) this is the plain original flow: a file path, a "Read"
    button, then the dropdowns once it succeeds.

    With ``show_embedded_option`` (still possible — either not yet known while
    the PCA tab's own loader is showing, or already confirmed via
    ``has_embedded_annotation_cols``), three buttons do double duty as both the
    mode choice and the "Read" step: "Use annotation from extra file" always
    reads the path below and uses only it; "Use annotation from eigenvec file"
    and "Combine annotation from eigenvec and extra file" only make sense once
    the eigenvec is confirmed to have its own columns — see
    callbacks/setup.py:read_eigenvec for the live reveal while still on the
    PCA tab's loader.
    """
    by = _actions_by_dest()
    if not show_embedded_option:
        return dbc.Container(
            [
                html.H4('Load annotation data', className='mt-3'),
                html.P('Optional metadata (regions, coordinates, dates, …). '
                       'Load the eigenvec first (PCA tab).', className='text-muted'),
                dcc.Store(id='annotation-source-store', data='file'),
                _file_row('Annotation file', args, by['annotation'], 'browse-annotation',
                          'Type a server-side path, or Browse.'),
                html.Div(dbc.Button('Read', id='read-annotation-btn', color='secondary',
                                    n_clicks=0), className='my-2'),
                html.Div(id='embedded-annotation-status', className='mb-2'),
                _annotation_second_step(args),
            ],
            style={'maxWidth': '760px'},
        )
    embedded_buttons = html.Div(
        [
            dbc.Button('Use annotation from eigenvec file',
                       id='use-embedded-annotation-btn', color='secondary',
                       n_clicks=0, className='me-2 mb-2'),
            dbc.Button('Combine annotation from eigenvec and extra file',
                       id='use-combine-annotation-btn', color='secondary',
                       n_clicks=0, className='me-2 mb-2'),
        ],
        id='embedded-annotation-section',
        className='d-flex flex-wrap',
        style={} if has_embedded_annotation_cols else {'display': 'none'},
    )
    file_help = ('Type a server-side path, or Browse. Only needed for "Use annotation '
                'from extra file" or "Combine…" below.')
    return dbc.Container(
        [
            html.H4('Load annotation data', className='mt-3'),
            html.P('Optional metadata (regions, coordinates, dates, …). '
                   'Load the eigenvec first (PCA tab).', className='text-muted'),
            dcc.Store(id='annotation-source-store', data='file'),
            _file_row('Annotation file', args, by['annotation'], 'browse-annotation', file_help),
            html.Div(
                [
                    dbc.Button('Use annotation from extra file',
                               id='use-file-annotation-btn', color='secondary',
                               n_clicks=0, className='me-2 mb-2'),
                    embedded_buttons,
                ],
                className='d-flex flex-wrap my-2',
            ),
            html.Div(id='embedded-annotation-status', className='mb-2'),
            _annotation_second_step(args),
        ],
        style={'maxWidth': '760px'},
    )


def settings_panel(args):
    """Settings-tab content: *every* CLI option + a Refresh (relaunch) button.

    Unlike the loader panels — which only exist while their file is missing —
    this lists the file/column parameters too, and it is always present. That
    makes it the one place to change e.g. --latitude/--longitude/--time on an
    app whose data is already loaded.
    """
    by = _actions_by_dest()

    def rows(dests):
        # Strip leading '--' from CLI option names for cleaner display.
        return [_labeled_row(by[d].option_strings[0].lstrip('-'),
                             _field_component(by[d], args, 'settings-arg'), by[d].help)
                for d in dests if d in by]

    other = [d for d in all_arg_names() if d not in PRIMARY_ARGS]
    return html.Div(
        [
            html.Div(
                [
                    html.H4('Settings', className='mt-3'),
                    html.P('Every parameter, including those set while loading. '
                           'Click Refresh to relaunch with the current values.',
                           className='text-muted'),
                    html.H6('Eigenvec', className='mt-3 text-muted'),
                    *rows(EIGENVEC_FIELDS),
                    html.H6('Annotation', className='mt-4 text-muted'),
                    *rows(ANNOTATION_FIELDS),
                    html.H6('Other options', className='mt-4 text-muted'),
                    *rows(other),
                    html.Div(dbc.Button('Refresh', id='settings-apply-btn', color='primary',
                                        n_clicks=0), className='mt-3'),
                    html.Div(id='settings-status', className='mt-2'),
                ],
                style={'maxHeight': 'calc(100vh - 120px)', 'overflowY': 'auto', 'paddingRight': '8px',
                       'maxWidth': '760px'},
            ),
        ],
    )


def file_browser_modal():
    """Server-side file-browser modal, shared by the Browse buttons."""
    return dbc.Modal(
        [
            dbc.ModalHeader(dbc.ModalTitle('Select a file')),
            dbc.ModalBody([
                html.Div(id='file-modal-cwd', className='text-muted small mb-2',
                         style={'wordBreak': 'break-all'}),
                html.Div(id='file-modal-list',
                         style={'maxHeight': '50vh', 'overflowY': 'auto'}),
            ]),
            dbc.ModalFooter(dbc.Button('Cancel', id='file-modal-cancel',
                                       color='secondary', n_clicks=0)),
        ],
        id='file-modal', is_open=False, size='lg', scrollable=True,
    )


def setup_stores():
    """Stores/dummies backing the loaders (relaunch trigger + browser state)."""
    return [
        dcc.Store(id='file-browser'),
        dcc.Store(id='relaunch-store'),
        html.Div(id='relaunch-poll-dummy', style={'display': 'none'}),
    ]
