"""
File-loader / settings panels shown inside the app's tabs when data is missing.

When the app is launched without ``--eigenvec`` (or without an annotation), the
PCA / Annotation tabs host these loader panels instead of the plots/table, and a
"Settings" tab hosts the remaining CLI options. The user points at server-side
file paths (typing, or via the Browse file-browser modal), reads their columns,
and clicks Load — which relaunches the process with the composed arguments (see
``callbacks/setup.py`` and ``relaunch.py``).

The Settings fields are generated by introspecting the argparse parser
(``args.create_parser``) so the form stays in sync with the CLI automatically.
"""

import argparse

import dash_bootstrap_components as dbc
from dash import html, dcc

from ..args import create_parser, float_0_1


# Field groupings by CLI dest.
EIGENVEC_FIELDS = ['eigenvec', 'eigenvecID', 'selectedID']
ANNOTATION_DEPENDENT = ['annotationID', 'latitude', 'longitude', 'time', 'group', 'group_shape']
ANNOTATION_FIELDS = ['annotation'] + ANNOTATION_DEPENDENT
PRIMARY_ARGS = EIGENVEC_FIELDS + ANNOTATION_FIELDS
# Internal flags not shown as form fields.
_INTERNAL_ARGS = ['setup']


def settings_arg_names():
    """CLI dests that belong to the Settings tab (everything not a file/column)."""
    return [a.dest for a in create_parser()._actions
            if a.option_strings and a.dest not in ('help',)
            and a.dest not in PRIMARY_ARGS and a.dest not in _INTERNAL_ARGS]


def _actions_by_dest():
    return {a.dest: a for a in create_parser()._actions if a.option_strings}


def _arg(name):
    """Pattern-matching id so one callback can collect every field via ALL."""
    return {'type': 'setup-arg', 'name': name}


def _initial(args, dest, fallback=None):
    """Prefill value: honour any args passed alongside the missing --eigenvec."""
    val = getattr(args, dest, None)
    return val if val is not None else fallback


def _field_component(action, args):
    """Build the input component for one argparse action, prefilled from args."""
    dest = action.dest
    comp_id = _arg(dest)
    default = _initial(args, dest, action.default)

    if isinstance(action, argparse._StoreTrueAction) or action.nargs == 0:
        return dbc.Checkbox(id=comp_id, value=bool(default))
    if action.choices is not None:
        return dcc.Dropdown(
            id=comp_id, clearable=False, value=default,
            options=[{'label': str(c), 'value': c} for c in action.choices],
        )
    if action.type is int:
        return dbc.Input(id=comp_id, type='number', step=1, value=default)
    if action.type in (float, float_0_1):
        return dbc.Input(id=comp_id, type='number', step=0.05, value=default)
    return dbc.Input(id=comp_id, type='text',
                     value='' if default is None else str(default))


def _labeled_row(label, component, help_text=None):
    return dbc.Row(
        [
            dbc.Label(label, width=4, style={'fontWeight': 500, 'textAlign': 'right'}),
            dbc.Col(
                [component] + ([html.Small(help_text, className='text-muted')]
                               if help_text else []),
                width=8,
            ),
        ],
        className='mb-2', align='center',
    )


def _file_row(label, args, action, browse_id, help_text):
    """A file-path row: text input + a Browse button opening the file modal."""
    return _labeled_row(
        label,
        dbc.InputGroup([
            _field_component(action, args),
            dbc.Button('Browse…', id=browse_id, color='light', n_clicks=0),
        ]),
        help_text,
    )


def _dependent_dropdown(args, dest, label, help_text):
    """A file-dependent dropdown, options filled after 'Read'."""
    value = _initial(args, dest)
    options = [{'label': value, 'value': value}] if value else []
    comp = dcc.Dropdown(id=_arg(dest), options=options, value=value,
                        clearable=True, placeholder='(read the file first)')
    return _labeled_row(label, comp, help_text)


def eigenvec_loader_panel(args):
    """PCA-tab content when no eigenvec is loaded: the eigenvec loader."""
    by = _actions_by_dest()
    eid_value = _initial(args, 'eigenvecID')
    eigenvec_id_dd = dcc.Dropdown(
        id=_arg('eigenvecID'), clearable=False, value=eid_value,
        options=[{'label': eid_value, 'value': eid_value}] if eid_value else [],
        placeholder='(read the file first)',
    )
    # selectedID may arrive as a ";"-joined string (e.g. after Restart); the
    # multi-select needs a list, and options must include the values to display.
    sel = _initial(args, 'selectedID')
    if isinstance(sel, str):
        sel = [s for s in sel.split(';') if s] or None
    sel_options = [{'label': s, 'value': s} for s in sel] if sel else []
    selected_dd = dcc.Dropdown(
        id=_arg('selectedID'), multi=True, options=sel_options, value=sel,
        placeholder='(all samples — read the file first)',
    )
    return dbc.Container(
        [
            html.H4('Load eigenvec data', className='mt-3'),
            html.P('Point at a PLINK eigenvec file to start the PCA.',
                   className='text-muted'),
            _file_row('Eigenvec file *', args, by['eigenvec'], 'browse-eigenvec',
                      'Type a server-side path, or Browse.'),
            html.Div(dbc.Button('Read', id='read-eigenvec-btn', color='secondary',
                                n_clicks=0), className='my-2'),
            html.Div(id='eigenvec-read-status', className='mb-2'),
            _labeled_row('Eigenvec ID column', eigenvec_id_dd,
                         'Defaults to the first column.'),
            _labeled_row('Selected IDs', selected_dd,
                         'Which samples start selected (leave empty for all).'),
            html.Div(dbc.Button('Load', id='pca-load-btn', color='primary',
                                size='lg', n_clicks=0), className='mt-3'),
            html.Div(id='pca-load-status', className='mt-2'),
        ],
        style={'maxWidth': '760px'},
    )


def annotation_loader_panel(args):
    """Annotation-tab content when no annotation is loaded: the annotation loader."""
    by = _actions_by_dest()
    return dbc.Container(
        [
            html.H4('Load annotation data', className='mt-3'),
            html.P('Optional metadata (regions, coordinates, dates, …). '
                   'Load the eigenvec first (PCA tab).', className='text-muted'),
            _file_row('Annotation file', args, by['annotation'], 'browse-annotation',
                      'Type a server-side path, or Browse.'),
            html.Div(dbc.Button('Read', id='read-annotation-btn', color='secondary',
                                n_clicks=0), className='my-2'),
            html.Div(id='annotation-read-status', className='mb-2'),
            _dependent_dropdown(args, 'annotationID', 'Annotation ID column',
                                'Column matching the eigenvec IDs.'),
            _dependent_dropdown(args, 'latitude', 'Latitude column',
                                'Enables the map when latitude + longitude are set.'),
            _dependent_dropdown(args, 'longitude', 'Longitude column', None),
            _dependent_dropdown(args, 'time', 'Time column', 'Enables the time plot.'),
            _dependent_dropdown(args, 'group', 'Group / colour column',
                                'Default grouping for colour.'),
            _dependent_dropdown(args, 'group_shape', 'Group / shape column',
                                'Default grouping for marker shape (categorical).'),
            html.Div(dbc.Button('Load', id='annotation-load-btn', color='primary',
                                size='lg', n_clicks=0), className='mt-3'),
            html.Div(id='annotation-load-status', className='mt-2'),
        ],
        style={'maxWidth': '760px'},
    )


def settings_panel(args):
    """Settings-tab content: all the other CLI options + an Apply (relaunch) button."""
    actions = [a for a in create_parser()._actions
               if a.option_strings and a.dest not in ('help',)
               and a.dest not in PRIMARY_ARGS and a.dest not in _INTERNAL_ARGS]
    # Strip leading '--' from CLI option names for cleaner display
    rows = [_labeled_row(a.option_strings[0].lstrip('-'), _field_component(a, args), a.help)
            for a in actions]
    return html.Div(
        [
            html.Div(
                [
                    html.H4('Settings', className='mt-3'),
                    html.P('Applied on the next Load, or click Apply to relaunch now.',
                           className='text-muted'),
                    *rows,
                    html.Div(dbc.Button('Apply', id='settings-apply-btn', color='primary',
                                        n_clicks=0), className='mt-3'),
                    html.Div(id='settings-status', className='mt-2'),
                ],
                style={'maxHeight': 'calc(100vh - 120px)', 'overflowY': 'auto', 'paddingRight': '8px',
                       'maxWidth': '760px'},
            ),
        ],
    )


def file_browser_modal():
    """Server-side file-browser modal, shared by the Browse buttons."""
    return dbc.Modal(
        [
            dbc.ModalHeader(dbc.ModalTitle('Select a file')),
            dbc.ModalBody([
                html.Div(id='file-modal-cwd', className='text-muted small mb-2',
                         style={'wordBreak': 'break-all'}),
                html.Div(id='file-modal-list',
                         style={'maxHeight': '50vh', 'overflowY': 'auto'}),
            ]),
            dbc.ModalFooter(dbc.Button('Cancel', id='file-modal-cancel',
                                       color='secondary', n_clicks=0)),
        ],
        id='file-modal', is_open=False, size='lg', scrollable=True,
    )


def setup_stores():
    """Stores/dummies backing the loaders (relaunch trigger + browser state)."""
    return [
        dcc.Store(id='file-browser'),
        dcc.Store(id='relaunch-store'),
        html.Div(id='relaunch-poll-dummy', style={'display': 'none'}),
    ]
